services:
  music-backend:
    container_name: music-backend-test
    image: music-backend:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
