version: '3.8'
services:
  music-backend:
    image: music-backend:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: test
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]  # replace with your health endpoint
      interval: 30s
      timeout: 10s
      retries: 3
